### ISSUE TITLE
Paypal Native Checkout In iOS

### ISSUE THREAD

**Issue by lovekeshsaxena** [paypal/paypalnativecheckout-docs#5]
My code is modular, project has multiple static library. 
I am facing two issue in integration of paypalnativecheckout.
1. Unable to install paypalnativecheckout by Pod in project. 
> Analyzing dependencies
> Pre-downloading: `paypal-nativecheckout` from `git@github.com:paypal/paypalcheckout-ios.git`, tag `1.2.0`
> 
> [!] Error installing paypal-nativecheckout
> [!] Failed to download 'paypal-nativecheckout'.

2. I tried to add the framework directly into a framework. It's unable to add because of non-module framework.
I tried to add header files into project header umbrella.

> include of non-modular header inside framework module 'PaymentCheckout': '/Users/***/Documents/Projects/####/####/paypal-nativecheckout/NativeCheckout.framework/Headers/PYPLCheckout.h'
> #import "NativeCheckout/PYPLCheckout.h"

Can you please help me to resolve this issue?

**Comment by dmikey** [comment]
Hey @lovekeshsaxena ! 

We are away of the desire to be able to produce module bitmarker apps with our SDK. We're currently working on rolling through another version of the SDK, please stay tuned for more information. We will ensure that these needs are met for you.

Feel free to join our Google Group, to stay on top of communications.

https://groups.google.com/forum/#!forum/paypalcheckout
