### ISSUE TITLE
download NativeCheckout.framework Issue

### ISSUE THREAD

**Issue by Ferrick90** [paypal/paypalnativecheckout-docs#7]
download NativeCheckout.framework the [url](https://github.com/paypal/paypalcheckout-ios/raw/master/NativeCheckout.framework.zip) was dead.

**Comment by dmikey** [comment]
It's totally dead. Thanks @Ferrick90 We're actually getting prepped to release a new version of our checkout. We've reduced the size by 90%! We'll be dropping it in the next few weeks, stay tuned!
